config/routes.rb
Bloglr::Application.routes.draw do

  resources :comments
  resources :posts
  resources :users, except: [:index]
  resources :ratings, only: [:create, :update]
  resources :sessions, only: [:new, :create, :destroy]

  root 'pages#home'
  get "/posts_:order", to: "posts#index"
  get "/posts_by_rating", to: "posts#index_by_rating"
  get "pages/home", path: "/home"
  get "pages/about", path: "/about"
  get "/tags", to: "tags#index"
  get "/tag/:name", to: "tags#show"
  get "/signup", to: 'users#new'
  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/profile', to: 'users#profile'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
  has_many :ratings
  has_many :rated_posts, through: :ratings, source: :posts

  validates :username, presence: true, length: {maximum: 20}, uniqueness: {case_sensitive: true}
  validates :password, length: {within: 6..40}
  validates_confirmation_of :password
  before_save :encrypt_password

  def has_password?(submitted_password)
    password == encrypt(submitted_password)
  end

  def self.authenticate(username, submitted_password)
    user = find_by_username(username)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private

  def encrypt_password
    self.salt = make_salt if new_record?
    self.password = encrypt(password)
  end

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, except: [:new, :create]
  before_action :correct_user, only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params.permit(:username, :password, :password_confirmation, :id)[:id])
    @posts = @user.posts
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # User signup
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to posts_path, notice: 'Your account was created successfully!' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def profile
    @posts = current_user.posts
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(user_params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

end

app/helpers/users_helper.rb
module UsersHelper
	def possessive(word)
    if word.end_with?('s')
      word + "'"
    else
     word + "'s"
    end
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br/>
    <%= f.text_field :username, required: true, placeholder: "(case-sensitive)" %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password, required: true, placeholder: "Min password length: 6" %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Password Confirmation" %><br />
    <%= f.password_field :password_confirmation, required: true, placeholder: "Min password length: 6" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/profile.html.erb
<h1>My Profile</h1>

<% @posts.each do |post| %>
    <article class="post">
        <header>
            <%= rating_display(post).html_safe %>
            <h3><%= post.title %></h3>
        </header>
        <p><%= raw post.content %></p>
        <footer>
            <% if post.comment_count > 0 %>
            <div class="left_comment">(<%= link_to "#{post.comment_count}", post_path(post) + "#comments" %>)</div>
            <% end %>
            <div class="actions">
                <span><%= print_post_time(post) %></span>
                <span> by <%= link_to(post.user.username, post.user) %></span>
            </div>
            <div class="actions">
                <span><small><%= link_to 'Read more...', post %></small></span>
            </div>
        </footer>
    </article>
<% end %>

app/views/users/show.html.erb
<h1><%= possessive(@posts.first.user.username) %> Posts</h1>

<% @posts.each do |post| %>
    <article class="post">
        <header>
            <%= rating_display(post).html_safe %>
            <h3><%= post.title %></h3>
        </header>
        <p><%= raw post.content %></p>
        <footer>
            <% if post.comment_count > 0 %>
            <div class="left_comment">(<%= link_to "#{post.comment_count}", post_path(post) + "#comments" %>)</div>
            <% end %>
            <div class="actions">
                <span><%= print_post_time(post) %></span>
                <span> by <%= post.user.username %></span>
                <span><%= link_to 'Read more...', post %></span>
            </div>
        </footer>
    </article>
<% end %>