config/routes.rb
Bloglr::Application.routes.draw do

  resources :comments
  resources :posts
  resources :users, except: [:index]
  resources :ratings, only: [:create, :update]
  resources :sessions, only: [:new, :create, :destroy]

  root 'pages#home'
  get "/posts_:order", to: "posts#index"
  get "/posts_by_rating", to: "posts#index_by_rating"
  get "pages/home", path: "/home"
  get "pages/about", path: "/about"
  get "/tags", to: "tags#index"
  get "/tag/:name", to: "tags#show"
  get "/signup", to: 'users#new'
  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/profile', to: 'users#profile'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :ratings
  has_many :raters, through: :ratings, source: :users
  has_and_belongs_to_many :tags, join_table: :posts_tags

  validates :title, presence: true
  validates :content, presence: true
  validates :user_id, presence: true
  after_save :parse_tags

  default_scope :order => 'posts.created_at DESC'

  # We parse the tags from the content and then replace them
  # with link versions, after which we add new tags to the db
  def parse_tags
      tags = find_tags
      tags.each do |tag|
        @tag = Tag.find_or_create_by(name: tag)
        @tag.posts << self
      end
  end

  def total_rating
      self.ratings.sum(:value)
  end

  # find tags within content
  def find_tags
      tags = []
      self[:content].scan(/#([\w][\w\-]{1,18}[\w]?)\b/i){
        tag = Regexp.last_match[1]
        tags << tag.downcase
      }
      tags
  end

  def comment_count
    self.comments.count
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_action :authenticate, except: [:index, :show]
    
    # GET /posts
    # GET /posts.json
    def index
		order = params[:order]
		@posts = Post.all
		@posts.sort_by! { |p| [p.total_rating, p.created_at] }.reverse! if order == "rated"
        @posts.each{|post|
            post[:content].gsub!(/#([\w][\w\-]{1,18}[\w]?)\b/i){
                tag = Regexp.last_match[1]
                "<a href=\"/tag/#{tag.downcase}\"><mark>##{tag}</mark></a>"
            }
        }
    end


    # GET /posts/1
    # GET /posts/1.json
    def show
		@post[:content].gsub!(/#([\w][\w\-]{1,18}[\w]?)\b/i){
            tag = Regexp.last_match[1]
            "<a href=\"/tag/#{tag}\"><mark>##{tag}</mark></a>"
        }
        @post[:content].gsub!(/(?:\n\r?|\r\n?)/, '<br/>')
    end

    # GET /posts/new
    def new
        @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        respond_to do |format|
            if @post.save
                format.html { redirect_to @post, notice: 'Post was successfully created.' }
                format.json { render action: 'show', status: :created, location: @post }
            else
                format.html { render action: 'new' }
                format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
        respond_to do |format|
            if @post.update(post_params)
                format.html { redirect_to @post, notice: 'Post was successfully updated.' }
                format.json { head :no_content }
            else
                format.html { render action: 'edit' }
                format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
        @post.destroy
        respond_to do |format|
            format.html { redirect_to posts_url }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
        @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
        params.require(:post).permit(:title, :content, :created_at)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def rating_ballot
    if @rating = current_user.ratings.find_by_post_id(params[:id])
      @rating
    else
      current_user.ratings.new
    end
  end

  def current_user_rating
    if @rating = current_user.ratings.find_by_post_id(params[:id])
      @rating.value
    else
      "N/A"
    end
  end

  def print_post_time(post)
    distance_of_time_in_words((Time.now.utc - post.created_at).round) + " ago"
  end

  def rating_display(post)
    rating = post.total_rating
    if rating > 0
      "<span id='rating-value' class='rating-circle-green right'>#{rating}</span>"
    elsif rating < 0
      "<span id='rating-value' class='rating-circle-red right'>#{rating}</span>"
    else
      "<span id='rating-value' class='rating-circle-neutral right'>#{rating}</span>"
    end
  end

  def rating_between_arrows(post)
    rating = post.total_rating
    if rating > 0
      "<span id='rating-value1' class='rating-circle-green move'>#{rating}</span>"
    elsif rating < 0
      "<span id='rating-value1' class='rating-circle-red move'>#{rating}</span>"
    else
      "<span id='rating-value1' class='rating-circle-neutral move'>#{rating}</span>"
    end
  end

end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br/>
    <%= f.text_field :title, required: true, placeholder: "Enter the title of your post", :maxlength=>"50" %>
  </div>
  <div class="field">
    <%= f.label :content %><br/>
    <%= f.text_area :content, required: true, placeholder: "Enter the content of your post", :size=>"100x10"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%	rated_checked = false
	rated_checked = true if request.original_url.include?("rated")
%>
<form accept-charset="UTF-8" action="/posts" id="order_form" method="get">
  <b>Time:</b> <input id="order_time" name="order" type="radio" onchange="refreshPosts()" <%= raw "checked='true'" unless rated_checked %> value="time" />
  <b>Rated:</b> <input id="order_rated" name="order" type="radio" onchange="refreshPosts()" <%= raw "checked='true'" if rated_checked %> value="rated" />   
 </form>

<% @posts.each do |post| %>
    <article class="post">
        <header>
            <%= rating_display(post).html_safe %>
            <h3><%= post.title %></h3>
        </header>
        <p><%= raw post.content %></p>
        <footer>
            <% if post.comment_count > 0 %>
            <div class="left_comment">(<%= link_to "#{post.comment_count}", post_path(post) + "#comments" %>)</div>
            <% end %>
            <div class="actions">
                <span><%= print_post_time(post) %></span>
                <span> by <%= link_to(post.user.username, post.user) %></span>
            </div>
            <div class="actions">
                <span><small><%= link_to 'Read more...', post %></small></span>
            </div>
        </footer>
    </article>
<% end %>

app/views/posts/index_by_rating.html.erb
<% @posts.each do |post| %>
    <article class="post">
        <header>
            <%= rating_display(post).html_safe %>
            <h3><%= post.title %></h3>
        </header>
        <p><%= raw post.content %></p>
        <footer>
            <% if post.comment_count > 0 %>
            <div class="left_comment">(<%= link_to "#{post.comment_count}", post_path(post) + "#comments" %>)</div>
            <% end %>
            <div class="actions">
                <span><%= print_post_time(post) %></span>
                <span> by <%= link_to(post.user.username, post.user) %></span>
            </div>
            <div class="actions">
                <span><small><%= link_to 'Read more...', post %></small></span>
            </div>
        </footer>
    </article>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<article class="post">
  <header>
    <%= rating_display(@post).html_safe %>
    <h1><%= @post.title %> </h1>
  </header>
  <p><%= raw @post.content %></p>
  <footer class="actions">
    <span><%= print_post_time(@post) %></span>
    <span> by <%= link_to(@post.user.username, @post.user) %></span>
  </footer>
</article>
<% if correct_user(@post) %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>

<div class="ratings_holder">
  <%= render 'ratings/form' %>
</div>
<br/>
<div class="comment_create">
	<%= render 'comments/create' %>
</div>

<% @comments = @post.comments.order(created_at: :desc) %>
<% unless @comments.empty? %>
<br/>
<h3>Comments</h3>
  <section id="comments" class="comment_holder">
    <%= render 'comments/comment' %>
  </section>
<% end %>