config/routes.rb
Bloglr::Application.routes.draw do

  resources :comments
  resources :posts
  resources :users, except: [:index]
  resources :ratings, only: [:create, :update]
  resources :sessions, only: [:new, :create, :destroy]

  root 'pages#home'
  get "/posts_:order", to: "posts#index"
  get "/posts_by_rating", to: "posts#index_by_rating"
  get "pages/home", path: "/home"
  get "pages/about", path: "/about"
  get "/tags", to: "tags#index"
  get "/tag/:name", to: "tags#show"
  get "/signup", to: 'users#new'
  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/profile', to: 'users#profile'

end

app/views/layouts/application.html.erb
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Bloglr</title>
        <%= stylesheet_link_tag params[:controller], media: "all" %>
        <%= javascript_include_tag params[:controller] %>
        <%= csrf_meta_tags %>
        
        </head>
    <body>
        <main>
            <header id="top">
                <nav>
                    <%= link_to 'Bloglr', root_path %>
                    <%= link_to 'Posts', posts_path %>
                    <%= link_to 'New Post', new_post_path %>
                    <%= link_to 'Tags', tags_path %>
                    <% if current_user %>
                        <span class="right">Logged in as <%= current_user.username %><%= link_to "Profile", profile_path %><%= link_to "Sign Out", signout_path %></span>
                    <% else %>
                        <span class="right"><%= link_to "Sign up", signup_path %> | <%= link_to "Sign In", signin_path %></span>
                     <% end %>
                </nav>
            </header>
            <section id="middle">
                <% unless flash.empty? %>
                <header id ="notice" class="flash">
                    <% flash.each do |key, value| %>
                        <div class="flash<%= key %>"><%= value %></div>
                    <% end %>
                </header>
            <% end %>
                <%= yield %>
            </section>
        </main>

        <footer id="bottom">
            <section>            
                <% link = stylesheet_link_tag params[:controller]; regex = /href="([\w:\/\.-]*)"/ %>
                <% css_link = regex.match(link)[1] %>
                <a href="http://jigsaw.w3.org/css-validator/validator?uri=<%= request.host + css_link %>"><%= image_tag "css3.svg", :class => "grayscale" %></a><a href="http://validator.nu/?doc=<%= request.original_url %>"><%= image_tag "html5.svg", :class => "grayscale" %></a>
            </section>
        </footer>
    </body>
</html>